
title: kevin ma
email: kevthema@gmail.com
description:
url: ""
baseurl: "/sandbox"
sass:
  sass_dir: _sass
collections:
  projects:
    output: true
    permalink: /:path/
  misc:
    output: true
    permalink: /:path/
include: ['_pages']
markdown: kramdown
port: 8888
